Automated g4 rollback of changelist 279369564.
*** Reason for rollback ***

:-( rolling this back again because it breaks some targets.

java.lang.IllegalArgumentException: <nulltype> cannot be represented as a Class<?>.

My guess is that isType() is returning true when it should be returning false for null types, but I'll need to do more investigation.

*** Original change description ***

Use ElementVisitor rather than Element#getKind() in MoreElements#isType()

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=280489034