The EclipseHack doesn't work with the Eclipse batch compiler (EJC). The difference between the IDE compiler and the batch compiler lies in the enviroment class. This CL provides a different way to get the contents of a source file.
Also, to get the auto-value plugin to work with Eclipse:
- Annotation preprocessor plugin should include the annotation files itself (without it: noclassdeffounderror).
- Annotation preprocessor should not depend on any other classes that are not packaged: ImmutableSet
-------------
Created by MOE: http://code.google.com/p/moe-java
MOE_MIGRATED_REVID=62566202